name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  packages: write
  id-token: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install latest npm
        run: npm install -g npm@latest

      # Use npm install (not npm ci) because package-lock.json may not yet include @changesets/cli
      - name: Install dependencies
        run: npm install

      - name: Create Release Pull Request or Publish
        uses: changesets/action@v1
        with:
          version: npm run version
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ""
          NPM_CONFIG_PROVENANCE: "false"
